{
 "title": "Hargo Home",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "groupBy", "label": "Url", "query": "SHOW TAG KEYS" },
   {
    "name": "filterValue",
    "label": "Url",
    "query": "SELECT distinct \"URLShort\" FROM (SELECT \"Size\", \"URLShort\" FROM \"test_result\" WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$groupBy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "URLShort" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_result",
     "query": "SELECT mean(\"Latency\") FROM \"autogen\".\"test_result\" WHERE (\"URLShort\" =~ /^$filterValue$/) AND $timeFilter GROUP BY time($__interval), \"URLShort\" fill(null)",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "URLShort", "operator": "=~", "value": "/^$filterValue$/" }
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_$groupBy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "URLShort" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_result",
     "query": "SELECT count(Status) FROM \"autogen\".\"test_result\" WHERE (\"URLShort\" =~ /^$filterValue$/) AND $timeFilter GROUP BY time(1s), \"URLShort\" fill(null)",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "URLShort", "operator": "=~", "value": "/^$filterValue$/" }
     ]
    }
   ]
  },
  {
   "title": "Sucess",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sucess",
     "measurement": "test_result",
     "query": "SELECT count(\"Status\") as \"Sucess\" FROM \"autogen\".\"test_result\" WHERE (\"Status\" = 200) AND (\"URLShort\" =~ /^$filterValue$/)  AND $timeFilter",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "200" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sucess",
     "measurement": "test_result",
     "query": "SELECT count(\"Status\") as \"Sucess\" FROM \"autogen\".\"test_result\" WHERE (\"Status\"  >= 400) AND $timeFilter",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "200" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Sucess",
     "measurement": "test_result",
     "query": "select mean(Rate)  from (SELECT sum(Size)/1024 as \"Rate\" FROM \"autogen\".\"test_result\" WHERE (\"Status\" < 400) AND (\"URLShort\" =~ /^$filterValue$/)  AND $timeFilter group by time(1s))",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "200" }
     ]
    }
   ]
  }
 ]
}