{
 "title": "Hargo Tables",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "filterValue",
    "label": "Url",
    "query": "SELECT distinct \"URLShort\" FROM (SELECT \"Size\", \"URLShort\" FROM \"test_result\" WHERE $timeFilter)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_$groupBy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "URLShort" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_result",
     "query": "SELECT  mean(\"Latency\") as Latency ,max(Latency) as Max,min(Latency) as Min,STDDEV(Latency) as StdDev FROM \"autogen\".\"test_result\" WHERE (\"URLShort\" =~ /^$filterValue$/) AND $timeFilter GROUP BY  \"URLShort\" ",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "URLShort", "operator": "=~", "value": "/^$filterValue$/" }
     ]
    }
   ]
  },
  {
   "title": "TPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_$groupBy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "URLShort" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "test_result",
     "query": "select mean(TPS) as TPS,max(TPS) as Max,min(TPS) as Min,STDDEV(TPS) as StdDev  from (SELECT non_negative_derivative(count(Status),1s ) As TPS FROM \"autogen\".\"test_result\" WHERE (\"URLShort\" =~ /^$filterValue$/) AND $timeFilter GROUP BY time(1s), \"URLShort\" )   group  by URLShort",
     "select": [
      [
       { "params": [ "Status" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "URLShort", "operator": "=~", "value": "/^$filterValue$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "measurement": "test_result",
     "query": "SELECT \"Latency\", \"URLShort\" as \"Url\",Status  FROM \"autogen\".\"test_result\" WHERE (\"URLShort\" =~ /^$filterValue$/) AND  $timeFilter ",
     "select": [
      [
       { "params": [ "Latency" ], "type": "field" }
      ],
      [
       { "params": [ "URL" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "URLShort", "operator": "=~", "value": "/^$filterValue$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM \"autogen\".\"test_result\" WHERE (\"Status\"  >=400)  and (\"URLShort\" =~ /^$filterValue$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}